// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsymozitupumbmcxtxvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeW1veml0dXB1bWJtY3h0eHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzUwMTQsImV4cCI6MjA2ODAxMTAxNH0.ijfkQDP3WjRK-Nt6Ct2cByfoF6tup0MmChXbWiVzY0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});